---
apiVersion: v2
name: frp-operator
description: Expose your service in Kubernetes to the Internet with open source FRP!
version: 0.0.0-pr.2
appVersion: v0.7.0-librepod1
type: application
home: https://github.com/zufardhiyaulhaq/frp-operator

maintainers:
- name: Zufar Dhiyaulhaq
  email: zufardhiyaulhaq@gmail.com
  url: https://zufardhiyaulhaq.com
- name: LibrePod
  url: https://github.com/librepod
